// Chrome Extension Service Worker
// Handles cookie extraction from YouTube and posting to the Transmux backend.

const YOUTUBE_DOMAINS = [
  ".youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "music.youtube.com",
];

function toNetscapeCookie(c) {
  const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
  const includeSub = domain.startsWith(".");
  const path = c.path || "/";
  const secure = c.secure ? "TRUE" : "FALSE";
  const httpOnly = c.httpOnly ? "TRUE" : "FALSE";
  const expires = c.expirationDate
    ? Math.floor(c.expirationDate).toString()
    : "0";
  return `${domain}\t${includeSub ? "TRUE" : "FALSE"}\t${path}\t${secure}\t${expires}\t${c.name}\t${c.value}`;
}

async function extractYouTubeCookies() {
  const allCookies = [];
  for (const domain of YOUTUBE_DOMAINS) {
    try {
      const cookies = await chrome.cookies.getAll({ domain });
      allCookies.push(...cookies);
    } catch {}
  }
  const deduped = new Map();
  for (const c of allCookies) {
    const key = `${c.name}=${c.value}`;
    if (!deduped.has(key)) deduped.set(key, c);
  }
  const lines = [
    "# Netscape HTTP Cookie File",
    "# This file is auto-generated by Transmux Cookie Relay extension",
    "# https://curl.se/rfc/cookie_spec.html",
  ];
  for (const c of deduped.values()) {
    lines.push(toNetscapeCookie(c));
  }
  return lines.join("\n") + "\n";
}

// Use long-lived port connection instead of one-shot sendMessage
// This keeps the MV3 service worker alive during the full async flow
chrome.runtime.onConnect.addListener((port) => {
  if (port.name !== "transmux-cookies") return;
  port.onMessage.addListener((request) => {
    if (request.type !== "TRANSMUX_GET_COOKIES") return;
    const { backendUrl, jobId } = request;
    extractYouTubeCookies()
      .then((cookiesTxt) =>
        fetch(`${backendUrl}/api/cookies/${jobId}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ cookies: cookiesTxt }),
        })
      )
      .then((res) => res.json())
      .then((data) => {
        chrome.storage.local.set({ lastSent: Date.now(), lastSentStr: new Date().toLocaleString() });
        port.postMessage({ success: true, data });
      })
      .catch((err) => port.postMessage({ success: false, error: err.message }));
  });
});
