// Transmux Extension v5.0 — Background Service Worker
// Features: cookie relay, context menus, media detection, notifications, auto-sync

const BACKEND_DEFAULT = "https://KurbaniBoy-transmux.hf.space";
const YOUTUBE_DOMAINS = [".youtube.com", "www.youtube.com", "m.youtube.com", "music.youtube.com"];
const SUPPORTED_SITES = {
  "youtube.com": { label: "YouTube", actions: ["mp3", "mp4", "clip", "gif"] },
  "soundcloud.com": { label: "SoundCloud", actions: ["mp3", "opus", "flac"] },
  "vimeo.com": { label: "Vimeo", actions: ["mp4", "webm"] },
  "twitter.com": { label: "Twitter/X", actions: ["mp4", "gif"] },
  "x.com": { label: "Twitter/X", actions: ["mp4", "gif"] },
  "reddit.com": { label: "Reddit", actions: ["mp4", "gif"] },
  "tiktok.com": { label: "TikTok", actions: ["mp4", "mp3", "nowm"] },
  "instagram.com": { label: "Instagram", actions: ["mp4", "jpg"] },
};

// ─── Privacy Mode ───

async function isPrivacyMode() {
  return new Promise(resolve => {
    chrome.storage.local.get(["privacyMode"], (r) => resolve(!!r.privacyMode));
  });
}

// ─── Cookie Management ───

function toNetscapeCookie(c) {
  const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
  const includeSub = domain.startsWith(".");
  const path = c.path || "/";
  const secure = c.secure ? "TRUE" : "FALSE";
  const httpOnly = c.httpOnly ? "TRUE" : "FALSE";
  const expires = c.expirationDate ? Math.floor(c.expirationDate).toString() : "0";
  return `${domain}\t${includeSub ? "TRUE" : "FALSE"}\t${path}\t${secure}\t${expires}\t${c.name}\t${c.value}`;
}

async function extractYouTubeCookies() {
  const allCookies = [];
  for (const domain of YOUTUBE_DOMAINS) {
    try { allCookies.push(...await chrome.cookies.getAll({ domain })); } catch {}
  }
  const deduped = new Map();
  for (const c of allCookies) {
    const key = `${c.name}=${c.value}`;
    if (!deduped.has(key)) deduped.set(key, c);
  }
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by Transmux v5.0 Extension",
  ];
  for (const c of deduped.values()) lines.push(toNetscapeCookie(c));
  return lines.join("\n") + "\n";
}

async function sendCookies(backendUrl, jobId) {
  const cookiesTxt = await extractYouTubeCookies();
  const privacy = await isPrivacyMode();
  const res = await fetch(`${backendUrl}/api/cookies/${jobId}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ cookies: cookiesTxt, privacyMode: privacy }),
  });
  const data = await res.json();
  if (!privacy) {
    chrome.storage.local.set({ lastSent: Date.now(), lastSentStr: new Date().toLocaleString() });
  }
  return data;
}

async function sendPendingCookies(backendUrl) {
  const cookiesTxt = await extractYouTubeCookies();
  const res = await fetch(`${backendUrl}/api/cookies/pending`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ cookies: cookiesTxt }),
  });
  return res.json();
}

// ─── Context Menus ───

chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: "transmux-convert",
    title: "Convert with Transmux",
    contexts: ["link", "video", "audio"],
  });
  chrome.contextMenus.create({
    id: "transmux-mp3",
    title: "Download Audio (MP3)",
    contexts: ["link", "video", "audio"],
  });
  chrome.contextMenus.create({
    id: "transmux-mp4",
    title: "Download Video (MP4)",
    contexts: ["link", "video"],
  });
  chrome.contextMenus.create({
    id: "transmux-gif",
    title: "Create GIF from video",
    contexts: ["link", "video"],
  });
  chrome.contextMenus.create({
    id: "transmux-subtitles",
    title: "Extract Subtitles",
    contexts: ["link", "video"],
  });
  chrome.contextMenus.create({
    id: "transmux-separator",
    type: "separator",
    contexts: ["link", "video", "audio"],
  });
  chrome.contextMenus.create({
    id: "transmux-queue",
    title: "Send to Transmux Queue",
    contexts: ["link"],
  });
  chrome.contextMenus.create({
    id: "transmux-remux",
    title: "Instant Remux (Lossless MP4)",
    contexts: ["link", "video"],
  });
  chrome.contextMenus.create({
    id: "transmux-compress",
    title: "Compress Media",
    contexts: ["link", "video", "audio"],
  });
  chrome.contextMenus.create({
    id: "transmux-local-quick",
    title: "Open in Transmux",
    contexts: ["link"],
  });
  chrome.contextMenus.create({
    id: "transmux-stealth",
    title: "Stealth Download (browser-assisted)",
    contexts: ["link", "video", "audio"],
  });
});

chrome.contextMenus.onClicked.addListener((info, tab) => {
  const url = info.linkUrl || info.srcUrl || tab?.url;
  if (!url) return;

  const actionMap = {
    "transmux-convert": { action: "convert" },
    "transmux-mp3": { action: "convert", outputFormat: "mp3" },
    "transmux-mp4": { action: "convert", outputFormat: "mp4" },
    "transmux-gif": { action: "convert", outputFormat: "gif" },
    "transmux-subtitles": { action: "convert", burnSubtitles: true, outputFormat: "mkv" },
    "transmux-queue": { action: "queue" },
  };

  const action = actionMap[info.menuItemId];
  if (action) {
    openTransmuxWith(url, action);
  }

  // Instant Remux: open with copy codec (lossless)
  if (info.menuItemId === "transmux-remux") {
    openTransmuxWith(url, { action: "convert", outputFormat: "mp4", videoCodec: "copy", audioCodec: "copy" });
  }

  // Compress: open with target size hint
  if (info.menuItemId === "transmux-compress") {
    openTransmuxWith(url, { action: "convert", targetSize: "25" });
  }

  // Open in Transmux
  if (info.menuItemId === "transmux-local-quick") {
    openTransmuxWith(url, {});
  }

  // Stealth Download
  if (info.menuItemId === "transmux-stealth") {
    const jobId = crypto.randomUUID();
    stealthDownload(BACKEND_DEFAULT, url, jobId, tab?.id).catch(() => {
      openTransmuxWith(url, {});
    });
  }
});

function openTransmuxWith(url, params) {
  const base = BACKEND_DEFAULT;
  const query = new URLSearchParams({ url: url, ...params });
  chrome.tabs.create({ url: `${base}?${query.toString()}` });
}

// ─── Port Connections (cookies + auth, merged) ───

chrome.runtime.onConnect.addListener((port) => {
  if (port.name === "transmux-cookies") {
    port.onMessage.addListener(async (request) => {
      if (request.type === "TRANSMUX_GET_COOKIES") {
        try {
          const data = await sendCookies(request.backendUrl, request.jobId);
          port.postMessage({ success: true, data });
        } catch (err) {
          port.postMessage({ success: false, error: err.message });
        }
      }
      if (request.type === "TRANSMUX_SEND_PENDING_COOKIES") {
        try {
          const data = await sendPendingCookies(request.backendUrl);
          port.postMessage({ success: true, data });
        } catch (err) {
          port.postMessage({ success: false, error: err.message });
        }
      }
    });
  } else if (port.name === "transmux-auth") {
    port.onMessage.addListener((msg) => {
      if (msg.type === "AUTH_LOGIN") {
        chrome.storage.local.set({ authState: "authenticated", authUser: msg.user, authToken: msg.token });
        port.postMessage({ success: true });
      }
      if (msg.type === "AUTH_LOGOUT") {
        chrome.storage.local.remove(["authState", "authUser", "authToken"]);
        port.postMessage({ success: true });
      }
      if (msg.type === "AUTH_CHECK") {
        chrome.storage.local.get(["authState", "authUser", "authToken"], (r) => {
          port.postMessage({ state: r.authState, user: r.authUser, token: r.authToken });
        });
      }
    });
  }
});

// ─── Tab Media Detection ───

async function detectMediaInTab(tabId) {
  try {
    const results = await chrome.scripting.executeScript({
      target: { tabId },
      func: () => {
        const media = [];
        document.querySelectorAll("video").forEach(v => {
          if (v.src && v.src.startsWith("http")) media.push({ type: "video", src: v.src, duration: v.duration });
          v.querySelectorAll("source").forEach(s => {
            if (s.src && s.src.startsWith("http")) media.push({ type: "video", src: s.src });
          });
        });
        document.querySelectorAll("audio").forEach(a => {
          if (a.src && a.src.startsWith("http")) media.push({ type: "audio", src: a.src, duration: a.duration });
        });
        return media;
      },
    });
    return results?.[0]?.result || [];
  } catch { return []; }
}

// ─── Content Script Messages ───

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === "TRANSMUX_DETECT_SITE") {
    const tab = sender.tab;
    const url = tab?.url || "";
    const match = Object.entries(SUPPORTED_SITES).find(([domain]) => url.includes(domain));
    sendResponse({ detected: !!match, site: match ? match[1] : null, url });
  }
  if (message.type === "TRANSMUX_NOTIFY") {
    chrome.notifications.create({
      type: "basic",
      iconUrl: "icon.svg",
      title: message.title || "Transmux",
      message: message.message || "",
    });
  }
  if (message.type === "TRANSMUX_STEALTH_COMPLETE") {
    chrome.notifications.create({
      type: "basic",
      iconUrl: "icon.svg",
      title: "Stealth Download Complete",
      message: `Media from ${message.url?.slice(0, 50)}... downloaded via browser`,
    });
  }
  if (message.type === "TRANSMUX_AUTH_STATE") {
    // Store auth state from Clerk
    chrome.storage.local.set({ authState: message.authState, authUser: message.user });
    sendResponse({ stored: true });
  }
  if (message.type === "TRANSMUX_GET_AUTH") {
    chrome.storage.local.get(["authState", "authUser"], (r) => {
      sendResponse({ state: r.authState, user: r.authUser });
    });
    return true;
  }
});

// ─── Periodic Cookie Auto-Refresh ───

chrome.alarms.create("transmux-cookie-refresh", { periodInMinutes: 30 });

chrome.alarms.onAlarm.addListener(async (alarm) => {
  if (alarm.name === "transmux-cookie-refresh") {
    const cookiesTxt = await extractYouTubeCookies();
    const count = (cookiesTxt.match(/\n/g) || []).length - 2;
    chrome.storage.local.set({ cookieCount: Math.max(0, count), lastRefresh: Date.now() });
  }
});

// ─── Sync Accounts + Presets (B.13) ───

async function syncPresets(backendUrl, apiKey) {
  try {
    const res = await fetch(`${backendUrl}/api/sync/presets?key=${encodeURIComponent(apiKey)}`);
    const data = await res.json();
    return data;
  } catch { return { success: false, error: "Backend unreachable" }; }
}

async function savePresets(backendUrl, apiKey, presets) {
  try {
    const res = await fetch(`${backendUrl}/api/sync/presets`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ key: apiKey, presets }),
    });
    return res.json();
  } catch { return { success: false }; }
}

async function syncHistory(backendUrl, apiKey) {
  try {
    const res = await fetch(`${backendUrl}/api/sync/history?key=${encodeURIComponent(apiKey)}`);
    return res.json();
  } catch { return { success: false }; }
}

async function saveHistory(backendUrl, apiKey, history) {
  try {
    const res = await fetch(`${backendUrl}/api/sync/history`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ key: apiKey, history }),
    });
    return res.json();
  } catch { return { success: false }; }
}

// ─── Stealth Download Engine (B.14) ───

async function stealthDownload(backendUrl, url, jobId, tabId) {
  try {
    if (tabId) {
      await chrome.tabs.sendMessage(tabId, { type: "TRANSMUX_STEALTH_DOWNLOAD", url, jobId, backendUrl });
      return { success: true };
    }
    throw new Error("No tab ID provided");
  } catch (err) {
    console.error("[Stealth] Browser fetch failed, falling back to server:", err);
    // Fallback: tell server to download using yt-dlp impersonation
    const fallbackRes = await fetch(`${backendUrl}/api/stealth-download`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url, jobId }),
    });
    return fallbackRes.json();
  }
}

// ─── Startup: initial cookie count ───

(async () => {
  try {
    const cookiesTxt = await extractYouTubeCookies();
    const count = (cookiesTxt.match(/\n/g) || []).length - 2;
    chrome.storage.local.set({ cookieCount: Math.max(0, count), lastRefresh: Date.now() });
  } catch {}
})();
