// Transmux v5.0 Popup — Dashboard & Quick Actions

const BACKEND_DEFAULT = "https://KurbaniBoy-transmux.hf.space";
const YOUTUBE_DOMAINS = [".youtube.com", "www.youtube.com", "m.youtube.com", "music.youtube.com"];

function $(id) { return document.getElementById(id); }

let dashboardInterval;
let healthCache = { ok: null, timestamp: 0 };
const HEALTH_CACHE_TTL = 30000;
let pendingClipboardUrl = null;

// ─── Logging ───

function log(msg, type = "info") {
  const el = $("log");
  if (!el) return;
  const line = document.createElement("div");
  line.className = "log-line";
  const ts = new Date().toLocaleTimeString();
  const colors = { info: "#64748b", success: "#22c55e", error: "#ef4444", warn: "#eab308" };
  line.style.color = colors[type] || colors.info;
  line.textContent = `[${ts}] ${msg}`;
  el.prepend(line);
  while (el.children.length > 20) el.removeChild(el.lastChild);
}

function logError(msg) { log(msg, "error"); }
function logSuccess(msg) { log(msg, "success"); }

// ─── Cookie Management ───

async function countCookies() {
  let all = [];
  for (const domain of YOUTUBE_DOMAINS) {
    try { all.push(...await chrome.cookies.getAll({ domain })); } catch {}
  }
  const deduped = new Map();
  for (const c of all) {
    const key = `${c.name}=${c.value}`;
    if (!deduped.has(key)) deduped.set(key, c);
  }
  return deduped.size;
}

async function sendCurrentCookies() {
  log("Sending cookies to Transmux...");
  const backends = [BACKEND_DEFAULT];
  let success = false;
  for (const backend of backends) {
    try {
      const cookiesTxt = await extractCookiesTxt();
      const res = await fetch(`${backend}/api/cookies/pending`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ cookies: cookiesTxt }),
      });
      const data = await res.json();
      if (data.success) {
        logSuccess(`Cookies sent! (${backend})`);
        chrome.storage.local.set({ lastSent: Date.now(), lastSentStr: new Date().toLocaleString() });
        success = true;
        break;
      }
    } catch {}
  }
  if (!success) {
    logError("Could not reach Transmux backend");
  }
  return success;
}

async function extractCookiesTxt() {
  let all = [];
  for (const domain of YOUTUBE_DOMAINS) {
    try { all.push(...await chrome.cookies.getAll({ domain })); } catch {}
  }
  const deduped = new Map();
  for (const c of all) {
    const key = `${c.name}=${c.value}`;
    if (!deduped.has(key)) deduped.set(key, c);
  }
  const lines = ["# Netscape HTTP Cookie File", "# Generated by Transmux v5.0"];
  for (const c of deduped.values()) {
    const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
    const includeSub = domain.startsWith(".");
    const path = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const httpOnly = c.httpOnly ? "TRUE" : "FALSE";
    const expires = c.expirationDate ? Math.floor(c.expirationDate).toString() : "0";
    lines.push(`${domain}\t${includeSub ? "TRUE" : "FALSE"}\t${path}\t${secure}\t${expires}\t${c.name}\t${c.value}`);
  }
  return lines.join("\n") + "\n";
}

// ─── Tab Detection ───

async function detectCurrentTab() {
  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    return tab;
  } catch { return null; }
}

function detectSiteFromUrl(url) {
  const sites = {
    "youtube.com": { label: "YouTube", icon: "▶️" },
    "soundcloud.com": { label: "SoundCloud", icon: "🎵" },
    "vimeo.com": { label: "Vimeo", icon: "🎬" },
    "twitter.com": { label: "Twitter/X", icon: "🐦" },
    "x.com": { label: "Twitter/X", icon: "🐦" },
    "reddit.com": { label: "Reddit", icon: "👽" },
    "tiktok.com": { label: "TikTok", icon: "📱" },
    "instagram.com": { label: "Instagram", icon: "📷" },
    "twitch.tv": { label: "Twitch", icon: "🎮" },
  };
  for (const [domain, info] of Object.entries(sites)) {
    if (url?.includes(domain)) return info;
  }
  return null;
}

async function detectMediaInTab(tabId) {
  try {
    if (!chrome.scripting?.executeScript) {
      log("Script injection not available (restricted page)", "warn");
      return [];
    }
    const results = await chrome.scripting.executeScript({
      target: { tabId },
      func: () => {
        const items = [];
        document.querySelectorAll("video").forEach(v => {
          if (v.src && v.src.startsWith("http")) {
            items.push({ type: "video", src: v.src, duration: v.duration, poster: v.poster, title: document.title });
          }
          v.querySelectorAll("source").forEach(s => {
            if (s.src && s.src.startsWith("http")) items.push({ type: "video", src: s.src });
          });
        });
        document.querySelectorAll("audio").forEach(a => {
          if (a.src && a.src.startsWith("http")) {
            items.push({ type: "audio", src: a.src, duration: a.duration, title: document.title });
          }
        });
        return items;
      },
    });
    return results?.[0]?.result || [];
  } catch (e) {
    logError(`Media detection failed: ${e.message}`);
    return [];
  }
}

// ─── URL to Queue ───

function openTransmux(url, params = {}) {
  const query = new URLSearchParams({ url, ...params });
  chrome.tabs.create({ url: `${BACKEND_DEFAULT}?${query.toString()}` });
}

// ─── UI Updates ───

async function updateCookieUI() {
  const count = await countCookies();
  $("cookie-count").textContent = count;
  if (count > 0) {
    $("cookie-count").style.color = "#22c55e";
  } else {
    $("cookie-count").style.color = "#ef4444";
  }

  chrome.storage.local.get(["lastSent", "cookieCount"], (result) => {
    const sentCount = result.lastSent ? "✓" : "0";
    $("cookie-sent-count").textContent = result.lastSent ? "✓" : "0";
  });
}

async function updateSiteDetection() {
  const tab = await detectCurrentTab();
  const badge = $("site-badge");
  if (!tab?.url) {
    badge.textContent = "❌ No page";
    badge.className = "site-badge";
    return;
  }

  const site = detectSiteFromUrl(tab.url);
  if (site) {
    badge.innerHTML = `${site.icon} ${site.label} detected`;
    badge.className = "site-badge active";
  } else {
    const domain = new URL(tab.url).hostname.replace("www.", "");
    badge.textContent = `🌐 ${domain}`;
    badge.className = "site-badge";
  }
}

async function updateMediaDetection() {
  const tab = await detectCurrentTab();
  if (!tab?.id) return;

  const mediaItems = await detectMediaInTab(tab.id);
  const container = $("media-content");
  container.innerHTML = "";

  if (mediaItems.length === 0) {
    container.innerHTML = `
      <div class="no-media">
        <div class="no-media-icon">🎥</div>
        <div>No media detected on this page</div>
        <div style="margin-top:4px;font-size:10px;color:#64748b">Try YouTube, SoundCloud, or any page with video/audio</div>
      </div>`;
    return;
  }

  const seen = new Set();
  mediaItems.forEach((item, idx) => {
    if (seen.has(item.src)) return;
    seen.add(item.src);

    const card = document.createElement("div");
    card.className = "media-card";
    const icon = item.type === "video" ? "🎬" : "🎵";
    const title = item.title || `Media ${idx + 1}`;
    const duration = item.duration ? `${Math.floor(item.duration)}s` : "";
    const shortSrc = item.src.length > 50 ? item.src.slice(0, 50) + "..." : item.src;

    let thumbnailHtml = "";
    if (item.type === "video") {
      thumbnailHtml = `<div class="thumb-wrap">`;
      if (item.poster) {
        thumbnailHtml += `<div class="thumb-skel">🎬</div>`;
        thumbnailHtml += `<img src="${item.poster}" alt="" loading="lazy" onload="this.previousElementSibling.style.display='none'" onerror="this.style.display='none'" />`;
      } else {
        thumbnailHtml += `<div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:20px;background:linear-gradient(135deg,#1e293b,#334155);animation:pulse 2s infinite">🎬</div>`;
      }
      thumbnailHtml += `</div>`;
    }

    card.innerHTML = `
      ${thumbnailHtml}
      <div class="media-title">${icon} ${title}</div>
      <div class="media-meta">${duration ? `⏱ ${duration} · ` : ""}${shortSrc}</div>
      <div class="media-actions">
        <button class="btn btn-primary btn-sm media-convert" data-src="${item.src}">🔄 Convert</button>
        <button class="btn btn-success btn-sm media-mp3" data-src="${item.src}">🎵 MP3</button>
        ${item.type === "video" ? `<button class="btn btn-amber btn-sm media-gif" data-src="${item.src}">🎞 GIF</button>` : ""}
        <button class="btn btn-outline btn-sm media-copy" data-src="${item.src}">📋 Copy URL</button>
      </div>`;

    container.appendChild(card);
  });
}

// ─── Health Check with Cache ───

async function checkHealth() {
  const now = Date.now();
  if (healthCache.ok !== null && now - healthCache.timestamp < HEALTH_CACHE_TTL) {
    return healthCache.ok;
  }
  try {
    const res = await fetch(`${BACKEND_DEFAULT}/api/health`);
    healthCache = { ok: res.ok, timestamp: now };
    return res.ok;
  } catch {
    healthCache = { ok: false, timestamp: now };
    return false;
  }
}

// ─── Initialize ───

document.addEventListener("DOMContentLoaded", () => {
  // Quick Actions
  $("action-mp3").addEventListener("click", async () => {
    const tab = await detectCurrentTab();
    if (tab?.url) openTransmux(tab.url, { outputFormat: "mp3" });
  });
  $("action-mp4").addEventListener("click", async () => {
    const tab = await detectCurrentTab();
    if (tab?.url) openTransmux(tab.url, { outputFormat: "mp4" });
  });
  $("action-gif").addEventListener("click", async () => {
    const tab = await detectCurrentTab();
    if (tab?.url) openTransmux(tab.url, { outputFormat: "gif" });
  });
  $("action-clip").addEventListener("click", async () => {
    const tab = await detectCurrentTab();
    if (tab?.url) openTransmux(tab.url, { action: "clip" });
  });
  $("action-remux").addEventListener("click", async () => {
    const tab = await detectCurrentTab();
    if (tab?.url) openTransmux(tab.url, { outputFormat: "mp4", videoCodec: "copy", audioCodec: "copy" });
  });

  // Cookie buttons
  $("refresh-cookies").addEventListener("click", async () => {
    const btn = $("refresh-cookies");
    btn.disabled = true;
    btn.textContent = "🔄 Sending...";
    await sendCurrentCookies();
    await updateCookieUI();
    btn.disabled = false;
    btn.textContent = "🔄 Refresh Now";
  });

  $("test-cookies").addEventListener("click", async () => {
    const btn = $("test-cookies");
    btn.disabled = true;
    btn.textContent = "🔍 Checking...";
    const count = await countCookies();
    if (count > 0) {
      logSuccess(`Found ${count} YouTube cookies ✓`);
      chrome.storage.local.get("lastSentStr", (r) => {
        log(`Last sent: ${r.lastSentStr || "Never"}`);
      });
    } else {
      log("No YouTube cookies found. Sign in to YouTube first.");
    }
    btn.disabled = false;
    btn.textContent = "🔍 Test Cookies";
  });

  // Multi-Tab Batch Queue
  $("action-all-tabs").addEventListener("click", async () => {
    const btn = $("action-all-tabs");
    btn.disabled = true;
    btn.textContent = "⏳ Scanning...";
    try {
      const tabs = await chrome.tabs.query({ url: ["*://*.youtube.com/*", "*://*.soundcloud.com/*", "*://*.vimeo.com/*", "*://*.twitter.com/*", "*://*.x.com/*", "*://*.reddit.com/*", "*://*.tiktok.com/*", "*://*.instagram.com/*"] });
      const supported = tabs.filter(t => t.url && !t.url.includes("accounts.google"));
      if (supported.length === 0) {
        log("No supported tabs found", "warn");
        btn.textContent = "📑 All Tabs";
        btn.disabled = false;
        return;
      }
      log(`Sending ${supported.length} URLs to Transmux...`);
      for (const tab of supported) {
        openTransmux(tab.url, { action: "queue" });
      }
      logSuccess(`Sent ${supported.length} URLs to queue!`);
    } catch (e) {
      logError(`Batch queue failed: ${e.message}`);
    }
    btn.textContent = "📑 All Tabs";
    btn.disabled = false;
  });

  // Sync buttons
  $("sync-presets").addEventListener("click", () => doSync("presets"));
  $("sync-history").addEventListener("click", () => doSync("history"));

  // Privacy Mode
  chrome.storage.local.get(["privacyMode"], (result) => {
    const toggle = $("privacy-toggle");
    if (toggle) {
      toggle.checked = !!result.privacyMode;
      toggle.addEventListener("change", () => {
        chrome.storage.local.set({ privacyMode: toggle.checked });
        log(toggle.checked ? "🔒 Privacy Mode enabled" : "🔓 Privacy Mode disabled");
      });
    }
  });

  // Clipboard Detection
  chrome.storage.local.get(["detectedClipboardUrl", "detectedAt"], (result) => {
    if (result.detectedClipboardUrl && result.detectedAt && Date.now() - result.detectedAt < 60000) {
      pendingClipboardUrl = result.detectedClipboardUrl;
      log(`📋 Clipboard: ${result.detectedClipboardUrl.slice(0, 60)}...`);
      const container = $("media-content");
      if (container && container.querySelector(".no-media")) {
        const url = result.detectedClipboardUrl;
        const site = detectSiteFromUrl(url);
        const siteName = site?.label || "URL";
        container.innerHTML = `
          <div class="media-card">
            <div class="media-title">📋 Clipboard Detected: ${siteName}</div>
            <div class="media-meta">${url.slice(0, 60)}${url.length > 60 ? "..." : ""}</div>
            <div class="media-actions">
              <button class="btn btn-primary btn-sm" id="clipboard-convert">🔄 Convert</button>
              <button class="btn btn-success btn-sm" id="clipboard-mp3">🎵 MP3</button>
              <button class="btn btn-outline btn-sm" id="clipboard-clear">✕ Dismiss</button>
            </div>
          </div>`;
      }
    }
  });

  // Event Delegation for Media Container
  const container = $("media-content");
  if (container) {
    container.addEventListener("click", (e) => {
      const btn = e.target.closest("button");
      if (!btn) return;

      const src = btn.dataset.src;

      if (btn.classList.contains("media-convert")) {
        openTransmux(src);
      } else if (btn.classList.contains("media-mp3")) {
        openTransmux(src, { outputFormat: "mp3" });
      } else if (btn.classList.contains("media-gif")) {
        openTransmux(src, { outputFormat: "gif" });
      } else if (btn.classList.contains("media-copy")) {
        navigator.clipboard.writeText(src).then(() => {
          logSuccess("URL copied!");
        }).catch(() => logError("Copy failed"));
      } else if (btn.id === "clipboard-convert") {
        if (pendingClipboardUrl) openTransmux(pendingClipboardUrl);
      } else if (btn.id === "clipboard-mp3") {
        if (pendingClipboardUrl) openTransmux(pendingClipboardUrl, { outputFormat: "mp3" });
      } else if (btn.id === "clipboard-clear") {
        chrome.storage.local.remove("detectedClipboardUrl");
        location.reload();
      }
    });
  }

  // Initialize dashboard, detection, and status
  (async () => {
    $("status-dot").className = "status-dot online";
    $("status-label").textContent = "Active";

    await updateSiteDetection();
    await updateMediaDetection();
    await updateCookieUI();
    updateDashboard();

    dashboardInterval = setInterval(updateDashboard, 10000);

    const healthy = await checkHealth();
    if (healthy) {
      $("status-dot").className = "status-dot online";
      $("status-label").textContent = "Connected";
    } else {
      $("status-dot").className = "status-dot offline";
      $("status-label").textContent = "Offline";
    }

    log("Transmux v5.0 ready");
  })();
});

// Cleanup on popup close
window.addEventListener("unload", () => {
  if (dashboardInterval) {
    clearInterval(dashboardInterval);
    dashboardInterval = null;
  }
});
